# Generated by Django 4.1.10 on 2023-12-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('app_category', models.CharField(max_length=100)),
                ('reviewer_id', models.IntegerField()),
                ('auditor_id', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=25)),
                ('remark', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reviewer_assigned_date', models.DateField()),
                ('auditor_assigned_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
